MelihAltintas/vue3-openlayers

package-lock.json, src/components/sources/SourceImageWMS.vue, src/components/sources/index.js
Addition of Image WMS  source
Your implementation was missing ImageWMS source, this code adds this functionality
Missing functionality
working with mapserver wms implementation
=> Add Image WMS  source: ol-source-image-wms

src/components/layers/VectorLayer.vue, src/components/mapControls/ButtonControl.vue, src/components/mapControls/MousePositionControl.vue, src/components/mapControls/index.js
add Arbitrary observable properties to vectorlayer;
modify coordinateFormat's type in MouthPositionControl;
add ButtonControl;
First of all thank you for creating this awesome library,
and this is my first time to create a pr on github, 
If there is something wrong, please help me to correct it.
1.add Arbitrary observable properties to vectorlayer;
2.modify coordinateFormat's type in MouthPositionControl;
3.add ButtonControl;
1.add Arbitrary observable properties to vectorlayer;
According to https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html,
properties | Object.<string, *> \| undefined | Arbitrary observable properties. Can be accessed with #get() and #set().
So I want to pass some observable properties to the component to identify some characteristics of the …
=> add Arbitrary observable properties to vectorlayer;modify coordinateFormat's type in MouthPositionControl;add ButtonControl;

src/components/sources/SourceXYZ.vue
Missing attributions in xyz source added :)
above
they were missing now they do not :)
=> add attributions to xyz source

src/App.vue, src/components/layers/HeatmapLayer.vue, src/components/layers/index.js, src/components/sources/SourceVector.vue
Signed-off-by: José Luis Di Biase <josx@interorganic.com.ar>
Fixes #88 
Create a new layer called Heatmap ([ol/layer/Heatmap](https://openlayers.org/en/latest/apidoc/module-ol_layer_Heatmap-Heatmap.html))
I need to show heatmap for disease in my country. 
I have replicated [this openlayer example](https://openlayers.org/en/latest/examples/heatmap-earthquakes.html) in App.vue, and tested running `npm run dev`
=> Add Heatmap layer support

src/components/layers/HeatmapLayer.vue
=> fix(heatmaplayer): updating after change of properties

package-lock.json, src/App.vue, src/components/layers/BaseLayer.vue, src/components/layers/HeatmapLayer.vue
see: https://openlayers.org/en/latest/apidoc/module-ol_layer_Heatmap-Heatmap.html
closes #135
=> feat(ol-heatmap-layer): allow to define `gradient`

docs/.vitepress/theme/index.ts, package-lock.json, package.json
closes https://github.com/MelihAltintas/vue3-openlayers/issues/141
=> fix: integrate docs from https://github.com/MelihAltintas/vue3-openlayers-docs

docs/.vitepress/config.ts, docs/componentsguide/map/index.md, docs/componentsguide/mapcontrols/attribution/index.md, docs/componentsguide/mapcontrols/contextmenu/index.md, docs/componentsguide/mapcontrols/fullscreen/index.md, docs/componentsguide/mapcontrols/index.md, docs/componentsguide/mapcontrols/mouseposition/index.md, docs/componentsguide/mapcontrols/overviewmap/index.md, docs/componentsguide/mapcontrols/rotate/index.md, docs/componentsguide/mapcontrols/scaleline/index.md, docs/componentsguide/mapcontrols/swipe/index.md, docs/componentsguide/mapcontrols/zoom/index.md, docs/componentsguide/mapcontrols/zoomslider/index.md, docs/componentsguide/mapcontrols/zoomtoextent/index.md, docs/demo.md, docs/get-started.md, src/demos/MapControlDemo.vue
=> docs: update docs

index.d.ts
=> fix: remove trailing slash from import of ol/geom

docs/.vitepress/config.ts, docs/componentsguide/interactions/dragrotatezoom/index.md, src/demos/DragRotateZoomDemo.vue
=> docs: add docs for dragrotatezoom

docs/.vitepress/config.ts, docs/componentsguide/layers/heatmaplayer/index.md, docs/public/sitemap.xml, src/demos/HeatmapLayerDemo.vue
=> docs(ol-heatmap-layer): add documentation for ol-heatmap-layer

docs/.vitepress/config.ts, docs/componentsguide/sources/tilewms/index.md, docs/public/sitemap.xml, src/components/sources/SourceTileWMS.vue, src/components/sources/index.js, src/demos/TileWMSDemo.vue
=> feat(ol-source-tile-wms): add source for tiled WMS layer

docs/.vitepress/config.ts, docs/componentsguide/interactions/clusterselect/index.md, docs/public/sitemap.xml, src/components/interaction/ClusterSelectInteraction.vue
closes #176 and pass-through new properties from `ol-ext/ol.interaction.SelectCluster`
=> Interaction cluster select

docs/.vitepress/config.ts, docs/componentsguide/feature/index.md
=> docs(ol-feature): add separate documentation for `ol-feature`

docs/componentsguide/geometries/geompolygon/index.md, src/demos/PolygonDemo.vue
=> docs: describe polygon wholes (as LinearRings)

docs/.vitepress/config.ts, docs/componentsguide/geometries/geomcircle/index.md, docs/public/sitemap.xml, src/components/geometries/Circle.vue, src/components/geometries/index.js, src/demos/AppDemo.vue, src/demos/CircleDemo.vue
cherry-picked commit from @Filipe-Goulart
closes #138
obsoletes #139 
=> feat(ol-geom-circle): new geometry function

docs/componentsguide/geolocation/index.md
=> docs: fix geolocation demo scripts error

docs/.vitepress/config.ts, docs/componentsguide/sources/arcgisrest/index.md, docs/public/sitemap.xml, src/components/sources/SourceTileArcGisRest.vue, src/components/sources/index.js, src/demos/TileArcGISRestSourceDemo.vue
Added new feature [ol/source/TileArcGISRest](https://openlayers.org/en/latest/apidoc/module-ol_source_TileArcGISRest.html)
I need to use this kind of source in my project.
I tested the feature, getting the layer I needed for my project.
=> feat: add source TileArcGISRest

docs/componentsguide/layers/animatedclusterlayer/index.md
Reworded some sentences to help improve their accuracy and precision in order to better express the concepts being explained
These changes improve the readability of the docs, by improving the general English
N/A docs change
- [ X ] Documentation Update
- [ X ] My code follows the code style of this project.
- [ X ] My change requires a change to the documentation.
- [ X ] I have updated the documentation accordingly.
=> Update animatedclusterlayer, improve wording and fluency of explanation

src/components/animations/index.ts, src/components/geometries/index.ts, src/components/interaction/index.ts, src/components/layers/index.ts, src/components/map/index.ts, src/components/mapControls/index.ts, src/components/sources/index.ts, src/components/styles/index.ts
=> allow multiple plugin installation

src/components/layers/OlImageLayer.vue, src/components/layers/OlTileLayer.vue, src/components/layers/OlWebglTileLayer.vue
fix for #277 
opacity and visibility settings after initial setup did not work now they do :)
in browser and with demo in ticket
=> add handling of visibility and opacity fixes #277

src/components/styles/OlStyle.vue
=> Fixed return statement in OlStyle

docs/.vitepress/config.ts, docs/componentsguide/mapcontrols/search/index.md, src/components/mapControls/OlSearchControl.vue, src/components/mapControls/index.ts, src/composables/useControl.ts, src/demos/SearchControlDemo.vue, vite.config.ts
=> feat(ol-search-control): add search control

src/components/geometries/OlGeomLineString.vue, src/components/geometries/OlGeomMultiLineString.vue, src/components/geometries/OlGeomMultiPoint.vue, src/components/geometries/OlGeomMultiPolygon.vue, src/components/geometries/OlGeomPolygon.vue
Changed the coordinate type of geometric shapes. Now they are the same as in the documentation.
Bug fix (non-breaking change that fixes an issue).
=> fix geometries coordinates types

src/types.ts
=> Make `displayInLayerSwitcher` prop optional
