src/components/sources/SourceImageWMS.vue

Time Dimension for WMS Layers
Some WMS have a time dimension as well. This PR adds this functionality as an optional string prop to the SourceImageWMS component. 
Missing functionality
Tested the functionality on a private WMS. Works with and without a time prop.

Added time parameter to ol-source-image-wms

---

src/components/sources/SourceXYZ.vue

I've added the TileGrid as a property for the SourceXYZ component.
These changes made it possible for us to use the TileGrid and therefore custom xyz-sources.
For it to work you will have to create a new OL TileGrid instead of a plain object, so:
const tileGrid = new TileGrid({
...
});
instead of
const TileGrid = {
...
};
We were able to use TileGrids successfully with this solution. But I am by no means an OL expert, so please test it for yourself if I missed anything :)
I just added the TileGrid as a regular property for the SourceXYZ component like documented in the OL API:
https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html

Adds TileGrid

---

src/App.vue
src/components/layers/WebglPointsLayer.vue
src/components/layers/index.js
src/components/sources/SourceWebglPoints.vue
src/components/sources/index.js

add WebglPointsLayer and SourceWebglPoints
add WebglPointsLayer and SourceWebglPoints
When the openlayer renderer over 10000 points in vector layer without using cluster, the browser will be super lag.
according to https://openlayers.org/en/latest/examples/webgl-points-layer.html,
webgl layer is a solution
I add an example in App.vue by using geojson data from https://openlayers.org/en/latest/examples/webgl-points-layer.html
It worked!

add WebglPointsLayer and SourceWebglPoints

---

index.d.ts
package.json

Added basic typescript declaration for the module.
* Created typescript declaration file
* Added declarations that declare return values of the `inject` method provided by the plugin.
When using a module with typescript there are some types missing and can be declared.
Created new Nuxt 3 plugin, with next code:
```typescript
import OpenLayersMap from 'vue3-openlayers'
import 'vue3-openlayers/dist/vue3-openlayers.css'
export default defineNuxtPlugin((nuxtApp) => {
nuxtApp.vueApp.use(OpenLayersMap)
})
```
Then created a component with example code:
```typescript
export default {
setup() {
const center = ref([34, 39.13])
const projection = ref('EPSG:4326')
const zoom = ref(6)
const rotation = ref(0)
const format = inject('ol-format');
const geoJson = new format.GeoJSON();
...
```
Without the …

WIP: Typescript types declarations

---

src/components/interaction/SelectInteraction.vue

This MR adds support for `removeCondition`:
>A function that takes an MapBrowserEvent and returns a boolean to indicate whether that event should be handled. By default, this is never. Use this if you want to use different events for add and remove instead of toggle.
(from [ol docs](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html))
It's a useful feature when interacting specific feature for which the select interaction should not be allowed
Was not tested.

removeCondition support in SelectInteraction

---

docs/componentsguide/styles/icon/index.md
src/components/styles/Icon.vue

feat(ol-style-icon): add provide prop `anchorYUnits`

---

src/components/mapControls/index.js

Added missing MapControls RotateControl export.
Allows RotateControl to be imported from the MapControls space.
Relates to https://github.com/MelihAltintas/vue3-openlayers/issues/131#issuecomment-1487525511

MapControls: Added missing RotateControl export

---

README.md
docs/componentsguide/map/index.md
docs/componentsguide/mapcontrols/mouseposition/index.md
src/components/interaction/ClusterSelectInteraction.vue
src/components/interaction/DrawInteraction.vue
src/components/interaction/ModifyInteraction.vue
src/components/layers/VectorLayer.vue
src/components/layers/WebglPointsLayer.vue
src/components/map/Map.vue
src/components/mapControls/MousePositionControl.vue
src/components/sources/SourceBingMaps.vue
src/components/sources/SourceImageStatic.vue
src/components/sources/SourceImageWMS.vue
src/components/sources/SourceOSM.vue
src/components/sources/SourceTianDiTu.vue
src/components/sources/SourceWMTS.vue
src/components/styles/Style.vue
src/composables/usePropsAsObjectProperties.js

Breaking Changes and OpenLayers 7

---

docs/.vitepress/config.ts
docs/componentsguide/layers/vectorimagelayer/index.md
docs/public/sitemap.xml
package.json
src/components/layers/VectorImageLayer.vue
src/components/layers/index.js
src/components/sources/SourceWMTS.vue
src/demos/VectorSourceDemo4.vue

This adds a `ol-vector-image-layer` component that serves as a wrapper around the [VectorImageLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage-VectorImageLayer.html) layer class.
I added a new component that wraps the VectorImageLayer class and documentation for it.
The VectorImageLayer layer type has a very similar interface to VectorLayer, but it renders all of its features to an image before drawing it on the map, which results in vastly improved performance during dragging/zooming operations.  This is very useful when rendering thousands of features at once.
I've deployed a working demo of this component here: https://hatchbed.github.io/vue3-openlayers/componentsguide/layers/vectorimagelayer/
If you added a new component feature (layer, geom, source, etc.), …

Add ol-vector-image-layer component

---

src/components/interaction/OlDrawInteraction.vue

Fix Draw Interaction by correctly removing old interaction on changes, not new one.
Not tested

remove old draw-interaction, not new one

---

src/components/map/OlFeature.vue

Creating a new Feature results in removing any styling that has been applied to the feature. This can also be solved by adding more reactivity on the injected styledObj in OlStyle.
Please make sure that I do not break anything by removing the usage of `usePropsAsObjectProperties`. I did not figure out what it adds of value in this component. Is it possible to pass in the coordinates of the feature into the props.properties object? -> If so, then I break the functionality here
See https://github.com/MelihAltintas/vue3-openlayers/issues/128#issuecomment-1630472490 for details
Fixes #128

Fix: OlFeature do not create a new Feature on props.properties change

---

docs/componentsguide/styles/text/index.md
src/components/styles/OlStyleText.vue

Hey! First of all, thanks for this awesome library! :)
One thing I was missing is the ability to set `backgroundFill` and `backgroundStroke` options of [ol/style/Text](https://openlayers.org/en/latest/apidoc/module-ol_style_Text.html), so I added it.
- I added a new `backgroundFill` prop. It's type is `Color | ColorLike` so it's easy to pass just a color when using the component.
- I added a new `backgroundStoke` prop. It's type is `StrokeOptions`. When using the component, we can pass a plain object with proper fields.
- I had to modify the `createText` function's signature to be able to accept the new props. Originally it accepted a form of `Options` as argument, but since the 2 new props doesn't match that, I had to change to the type of this component's props.
- Modified the …

feat(ol-style-text): added backgroundFill and backgroundStroke props

---

src/composables/useControl.ts

allow using controls as childs of bar

---

docs/.vitepress/config.ts
docs/componentsguide/sources/tiledebug/index.md
docs/public/sitemap.xml
src/components/sources/OlSourceTileDebug.vue
src/components/sources/index.ts
src/demos/ProjectionRegisterDemo.vue
src/demos/TileDebugDemo.vue
vite.config.ts

feat(ol-source-tile-debug): provide new component for TileDebug

---

docs/componentsguide/styles/text/index.md
src/components/styles/OlStyleText.vue

Thank you for the awesome library, it has saved me a ton of work. I've been trying to style some labels over map markers, and realized that I was unable to set the color of the text nor the stroke. 
Upon further digging, I came across this [PR](https://github.com/MelihAltintas/vue3-openlayers/pull/223) so I followed the same template used there and just added the missing props.
These two props are important to style text, and `OlStyleText` already implements those.
I tested this by pointing my project's npm to my local copy and tested the color and stroke modifications according to usage.

feat(ol-style-text): added fill and stroke props

---

vite.config.ts

in vite (or rollup or vue?) index.css was renamed to `main.css`
Therefore `dist/styles.css` is missing in npm package
```ts
import 'vue3-openlayers/styles.css'
```
is not working like described in the documentation
checked if styles.css is generated by running `npm build`

fix(vite): styles export

---

README.md
docs/get-started.md
package-lock.json
package.json

Upgraded the `ol-contextmenu` dependency to v5.4.0 (was v5.3.0 previously).
Currently, setting up a project with the peerDependencies as listed in the README results in a dependency conflict because `ol=^9.0.0` is specified but ol-contextmenu 5.3.0 explicitly states `ol<=8.x`, which is fixed in the [5.4.0 version](https://github.com/jonataswalker/ol-contextmenu/releases/tag/5.4.0) that @d-koppenhagen submitted and has since been released. Therefore the `overrides` workaround in the _package.json_ is no longer necessary.
_Edit: I just realised there was already an issue for this: #308_
Honestly I haven't tested this at all, but as the upstream change doesn't change anything than this very thing, it should be fine.™️ 
I hope I did everything correctly as this is the first time I commit to …

Upgrade ol-contextmenu to v5.4.0

---

src/components/layers/OlTileLayer.vue
src/composables/usePropsAsObjectProperties.ts

- add toRefs quickfix in OlTileLayer.vue, props should not bei writeable, so I change the props to a ref. To really solve this issue it would be better to change the props to a model. But this would take a lot more time.
- make options  in usePropsAsObjectProperties.ts reactive to fix the warning in the console that it expected a reactive object and get a plain one.
Fix issue #396 and #393 
I run the vite test and the testet it in componentsguide/layers/tilelayer/

Fix Console Warnings

---

src/composables/useLayer.ts

Fix where opacity might sometimes be undefined. By the way, modified properties.visible.

Fix bug when layer's opacity is undefined.

---

package-lock.json
package.json

resolves vue3-openlayers depends on vulnerable version of jspdf #424
Update jspdf to resolve #424
See #424

chore: update jspdf to ^3.0.1
